# A simple workflow to run tests using pytest against supported Python versions

name: Tests
on:
  pull_request:
    branches-ignore:
      - docs
    paths-ignore:
      - 'docs/**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # We can't properly align to the VFX Reference Platform as this
        # requires glibc 2.17, which is older than any of the available
        # environments.
        # TODO(DF): Enable other platforms.
        # os: [ubuntu-20.04, windows-2019, macos-11]
        os: [ubuntu-20.04, windows-2019]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        # CY2022 (https://vfxplatform.com)
        python-version: 3.9

    - name: Cache conan packages
      id: cache-conan
      uses: actions/cache@v2
      with:
        path: ~/conan
        key: ${{ matrix.os }}-conan

    - name: Install dependencies (Unix)
      if: runner.os != 'Windows'
      # Configure the system and install library dependencies via conan
      # packages.
      run: |
        source resources/build/bootstrap-${{ matrix.os }}.sh

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      # Configure the system and install library dependencies via conan
      # packages.
      run: |
        cmd /C resources\build\bootstrap-${{ matrix.os }}.bat

    - name: Configure CMake build (Unix)
      if: runner.os != 'Windows'
      run: >
        cmake -S . -B build 
        --install-prefix $GITHUB_WORKSPACE/dist 
        --toolchain $HOME/conan/conan_paths.cmake 
        -DCMAKE_VERBOSE_MAKEFILE=ON 
        -DOPENASSETIO_ENABLE_TESTS=ON 
        -DOPENASSETIO_ENABLE_SANITIZER_ADDRESS=ON 
        -DOPENASSETIO_ENABLE_SANITIZER_UNDEFINED_BEHAVIOR=ON

    - name: Configure CMake build (Windows)
      if: runner.os == 'Windows'
      run: >
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        
        cmake -G Ninja -S . -B build --install-prefix %GITHUB_WORKSPACE%\dist
        --toolchain %USERPROFILE%\conan\conan_paths.cmake -DCMAKE_VERBOSE_MAKEFILE=ON
        -DOPENASSETIO_ENABLE_TESTS=ON
      shell: cmd

    - name: Build, install and test (Unix)
      if: runner.os != 'Windows'
      run: |
        cd build
        ctest -VV

    - name: Build, install and test (Windows)
      if: runner.os == 'Windows'
      run: |
        cd build
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        ctest -VV
      shell: cmd

  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Test
      run: |
        echo "::add-matcher::./.github/workflows/problem-matchers/doxygen.json"
        # Problem matches don't actually error a step, so we have to
        # manually check for warnings/errors at the end. Capture the
        # output so we can parse it later.
        set -o pipefail
        make -C doc 2>&1 | tee doxygen-log.txt
        echo "::remove-matcher owner=doxygen::"
        # Fail the job if we have Doxygen warning/error lines in the
        # output. NB: This is the same regex as doxygen.json, adapted
        # to work with GNU grep.
        ! grep -qE "^.*?/src/[^:]+:[0-9]+: ?[a-zA-Z]+: ?.*$" doxygen-log.txt

  business-language:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Check business language
      run: |
        # Check that the acronym version of OpenAssetIO isn't in use
        # in the code base, see:
        #   https://github.com/TheFoundryVisionmongers/OpenAssetIO/issues/153
        # NB: The quotes deliberately avoid the string in question
        # appearing in this file, and failing the test.
        ! grep -ir "o""aio" .

